# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1300, 755)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1300, 650))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        mainWindow.setFont(font)
        mainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("* {\n"
"    color: #343542;\n"
"    border: none;\n"
"}\n"
"\n"
"#leftMenuFrame {\n"
"    background-image: url(\":/images/images/sideLeft.png\");\n"
"    color: #eff9fe;\n"
"}\n"
"\n"
" #mainBody {\n"
"    background-image: url(\":/images/images/main.png\");\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QTableView {\n"
"    border: 1px solid #222;\n"
"    padding: 0px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 14px;\n"
"    background-color: #EEF;\n"
"    alternate-background-color: #424242;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #3388ff;\n"
"}\n"
"QTableView QTableCornerButton::section {\n"
"    background-color: #292929;\n"
"    border: 1px;\n"
"    padding: 0px\n"
"}\n"
"QHeaderView, QHeaderView::section {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    font-size: 15px;\n"
"    border: 1px solid #C4C4C3;\n"
"    padding: 0px\n"
"}\n"
"\n"
"\n"
"#cardsFrame QPushButton, #cardsFrame QLabel{\n"
"    color: #eff9fe;\n"
"}\n"
"\n"
"#homeTab, #consultingTab, #documentsTab, #privacyTab, #accountTab, #logoutTab, #patientsTab, #patientsListTab{\n"
"    background: transparent;\n"
"}\n"
"\n"
"#usersTab1, #usersTab2, #usersTab3, #usersTab4, #usersTab5 ,#usersTab6  {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#accountFrame, #scrollArea, #scrollAreaWidgetContents, #scrollArea_1, #scrollAreaWidgetContents_1, #scrollArea_2, #scrollAreaWidgetContents_2,  #scrollArea_3, #scrollAreaWidgetContents_3,  #scrollArea_4, #scrollAreaWidgetContents_4,  #scrollArea_5, #scrollAreaWidgetContents_5 {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#patientsDettalLabel  {\n"
"    border: 2px solid #C4C4C3;\n"
"    background: #EEF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#patientsTable , #patientsTable_4, #patientsTable_5, #patientsTable_6, #patientsTable_7{\n"
"    border-top: 2px solid #C4C4C3;\n"
"    border-left: 2px solid #C4C4C3;\n"
"    background: #EEF;\n"
"}\n"
"\n"
"#patientsTable QLabel, #patientsTable QWidget,\n"
"#patientsTable_4 QLabel, #patientsTable_4 QWidget,\n"
"#patientsTable_5 QLabel, #patientsTable_5 QWidget,\n"
"#patientsTable_6 QLabel, #patientsTable_6 QWidget,\n"
"#patientsTable_7 QLabel, #patientsTable_7 QWidget {\n"
"    border-right: 2px solid #C4C4C3;\n"
"    border-bottom: 2px solid #C4C4C3;\n"
"}\n"
"\n"
"#patientsTable QWidget QPushButton, #addUserBtn, #addUserBtn_3, #addUserBtn_4, #addUserBtn_5, #addUserBtn_6, #usersWidget QPushButton, #saveAddUserBtn,#saveEditUserBtn, #savePrivacyBtn{\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    padding: 5px;\n"
"    color: #eff9fe;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#patientsTable QWidget QPushButton:hover,  #addUserBtn:hover, #addUserBtn_3:hover, #addUserBtn_4:hover, #addUserBtn_5:hover, #addUserBtn_6:hover , #usersWidget QPushButton:hover,#saveAddUserBtn:hover,#saveEditUserBtn:hover,#savePrivacyBtn:hover{\n"
"    background-color: #2580be;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: transparent;\n"
"    color: #343542;\n"
"}\n"
"\n"
"QPlainTextEdit  {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #343542;\n"
"    border: 1px solid #9B9B9B ;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox , QDateEdit {\n"
"    background-color: #F9F8FC;\n"
"    padding: 5px;\n"
"    border: 1px solid #343542;\n"
"}\n"
"\n"
"#headerFrame {\n"
"    background-color: #F9F8FC;\n"
"}\n"
"\n"
"#searchFrame {\n"
"    background-color: #fefeff;\n"
"    border-radius: 20px;\n"
"    border: 2px solid #343542;\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"#accountBtn {\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#welcomeLbl {\n"
"    text-align: right;\n"
"}\n"
"\n"
"#card1, #card2, #card3, #card4, #card5 {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    border-radius: 20px;\n"
"    color: #eff9fe;\n"
"} \n"
"\n"
"QPushButton#homeBtn, #usersBtn, #documentsBtn, #privacyBtn, #accountLeftBtn, #logoutBtn{\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton#homeBtn,#usersBtn, #documentsBtn, #privacyBtn, #accountLeftBtn, #logoutBtn, #logoLbl {\n"
"    color: #EFF9FE;\n"
"}\n"
"\n"
"#welcomeLbl, #spaceLbl {\n"
"    color: #343542;\n"
"}\n"
"\n"
"QPushButton#homeBtn:hover, #usersBtn:hover, #documentsBtn:hover, #privacyBtn:hover, #accountLeftBtn:hover, #logoutBtn:hover,  #savePrivacyBtn:hover{    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    border-top-left-radius: 15px;\n"
"    color: #EFF9FE;\n"
"}\n"
"\n"
"QPushButton#homeBtn:selected, #usersBtn:selected, #documentsBtn:selected, #privacyBtn:selected, #accountLeftBtn:selected, #logoutBtn:selected{    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #eff9fe;\n"
"    border-top-left-radius: 15px;\n"
"}\n"
"\n"
"#medicalLbl, #infoLbl {    \n"
"    color: #343542;\n"
"}\n"
"\n"
"#medicalFrame, #infoFrame, #accountInfoFrame, #medicalContentTab2, #medicalContentTab3, #medicalContentTab4, #medicalContentTab5, #accountInfoContents, #accountInfoScrollArea, #accountInfoTab {    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#infoFrame QLineEdit, #medicalFrame QLineEdit, #addUserWidget QLineEdit, #setUserWidget QLineEdit, \n"
"#infoFrame QComboBox, #medicalFrame QComboBox , #addUserWidget QComboBox,  #setUserWidget QComboBox,\n"
"#infoFrame QDateEdit, #medicalFrame QDateEdit, #addUserWidget QDateEdit, #setUserWidget QDateEdit {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #343542;\n"
"    border: 1px solid #9B9B9B ;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#Frame QComboBox:selected, \n"
"#medicalFrame QComboBox:selected  {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #343542;\n"
"    border: 1px solid #9B9B9B ;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#accountContents {\n"
"    background: #F9F8FC;\n"
"}\n"
"\n"
"Line {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"\n"
"#pushButton_8,#pushButton_9, #pushButton_10, #pushButton_11, #pushButton_12  , #infoContentSaveBtn, #logoutBtnYes, #logoutBtnNo, #deleteUserBtnNo, #deleteUserBtnYes{\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    padding: 10px;\n"
"    color: #eff9fe;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#pushButton_8:hover,#pushButton_9:hover, #pushButton_10:hover, #pushButton_11:hover, #pushButton_12:hover, #infoContentSaveBtn:hover, #logoutBtnYes:hover, #logoutBtnNo:hover,  #deleteUserBtnNo:hover, #deleteUserBtnYes:hover {\n"
"    background-color: #2580be;\n"
"}\n"
"\n"
"#infoHomeBtn, #medicalHomeBtn, #medicalBtn QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #003542;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#infoHomeBtn:hover, #medicalHomeBtn:hover, #medicalBtn QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fefefe, stop: 0.4 #f8f8f8, stop: 0.5 #eaeaea, stop: 1.0 #fefefe);    \n"
"    color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    border-radius: 50px;\n"
"}\n"
"\n"
"#medicalContentLayout {\n"
"    background-color: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#medicalContentTab1 {    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#accountFrame {\n"
"    border: 2px solid #C2C7CB;\n"
"}\n"
"/***********************************************************/\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"border-top: 2px solid #C2C7CB;\n"
"background-color: transparent;\n"
"}\n"
"#mainTabWidget::tab-bar {\n"
"width: 1000px;\n"
"}\n"
"\n"
"#usersListTab::tab-bar {\n"
"width: 950px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"border: 2px solid #C4C4C3;\n"
"border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"min-width: 8ex;\n"
"padding: 2px;\n"
"color: #eff9fe;\n"
"height: 20px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"color: #343542;\n"
"}\n"
"QTabBar::tab:selected {\n"
"color: #343542;\n"
"border-color: #9B9B9B;\n"
"border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"QTabBar::tab:!selected {\n"
"margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"/* IMPORTANT: 8< Add the code above here 8< */\n"
"QTabBar::tab:selected {\n"
"/* expand/overlap to the left and right by 4px */\n"
"margin-left: -4px;\n"
"margin-right: -4px;\n"
"}\n"
"QTabBar::tab:first:selected {\n"
"margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"}\n"
"QTabBar::tab:last:selected {\n"
"margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"QTabBar::tab:only-one {\n"
"margin: 0; /* if there is only one tab, we don\'t want overlapping margins */\n"
"}\n"
"/***********************************************************/\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #2576be;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: #2576be;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: #2576be;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/***********************************************************/\n"
"\n"
"QCheckBox {\n"
"    color: #343542;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-color: #9B9B9B;\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    padding-bottom: 2px;\n"
"    padding-top: 2px;\n"
"    border-width:1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    color: #2586be;\n"
"        border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #343542;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #343542;\n"
"    background-color:transparent;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: #9B9B9B;\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    padding-bottom: 2px;\n"
"    padding-top: 2px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #343542;\n"
"        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    font-weight: bold;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #343542;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenu.sizePolicy().hasHeightForWidth())
        self.leftMenu.setSizePolicy(sizePolicy)
        self.leftMenu.setMinimumSize(QtCore.QSize(220, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(220, 16777215))
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenuFrame.sizePolicy().hasHeightForWidth())
        self.leftMenuFrame.setSizePolicy(sizePolicy)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalLayout_7.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.leftMenuFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.logoLbl = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logoLbl.setFont(font)
        self.logoLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLbl.setObjectName("logoLbl")
        self.horizontalLayout_8.addWidget(self.logoLbl)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.leftBtnFrame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBtnFrame.sizePolicy().hasHeightForWidth())
        self.leftBtnFrame.setSizePolicy(sizePolicy)
        self.leftBtnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBtnFrame.setObjectName("leftBtnFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.leftBtnFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.homeBtn = QtWidgets.QPushButton(self.leftBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.homeBtn.setFont(font)
        self.homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/others/home-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setIconSize(QtCore.QSize(50, 50))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_8.addWidget(self.homeBtn)
        self.usersBtn = QtWidgets.QPushButton(self.leftBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.usersBtn.setFont(font)
        self.usersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/others/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usersBtn.setIcon(icon1)
        self.usersBtn.setIconSize(QtCore.QSize(50, 50))
        self.usersBtn.setObjectName("usersBtn")
        self.verticalLayout_8.addWidget(self.usersBtn)
        self.privacyBtn = QtWidgets.QPushButton(self.leftBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.privacyBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.privacyBtn.setIcon(icon2)
        self.privacyBtn.setIconSize(QtCore.QSize(50, 50))
        self.privacyBtn.setObjectName("privacyBtn")
        self.verticalLayout_8.addWidget(self.privacyBtn)
        self.accountLeftBtn = QtWidgets.QPushButton(self.leftBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.accountLeftBtn.setFont(font)
        self.accountLeftBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_edit-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountLeftBtn.setIcon(icon3)
        self.accountLeftBtn.setIconSize(QtCore.QSize(50, 50))
        self.accountLeftBtn.setObjectName("accountLeftBtn")
        self.verticalLayout_8.addWidget(self.accountLeftBtn)
        self.verticalLayout_9.addWidget(self.leftBtnFrame, 0, QtCore.Qt.AlignTop)
        self.logoutFrame = QtWidgets.QFrame(self.frame_3)
        self.logoutFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoutFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoutFrame.setObjectName("logoutFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.logoutFrame)
        self.verticalLayout_10.setContentsMargins(0, 0, 2, 9)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.logoutBtn = QtWidgets.QPushButton(self.logoutFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.logoutBtn.setFont(font)
        self.logoutBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/others/exit-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutBtn.setIcon(icon4)
        self.logoutBtn.setIconSize(QtCore.QSize(50, 50))
        self.logoutBtn.setCheckable(False)
        self.logoutBtn.setChecked(False)
        self.logoutBtn.setObjectName("logoutBtn")
        self.verticalLayout_10.addWidget(self.logoutBtn)
        self.verticalLayout_9.addWidget(self.logoutFrame, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.verticalLayout_6.addWidget(self.leftMenuFrame)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerFrame.sizePolicy().hasHeightForWidth())
        self.headerFrame.setSizePolicy(sizePolicy)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.headerFrame.setObjectName("headerFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.headerFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spaceWidget = QtWidgets.QWidget(self.headerFrame)
        self.spaceWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.spaceWidget.setObjectName("spaceWidget")
        self.spaceLbl = QtWidgets.QLabel(self.spaceWidget)
        self.spaceLbl.setGeometry(QtCore.QRect(0, 0, 201, 69))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spaceLbl.setFont(font)
        self.spaceLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.spaceLbl.setObjectName("spaceLbl")
        self.gridLayout.addWidget(self.spaceWidget, 0, 0, 1, 1)
        self.welcomeWidget = QtWidgets.QWidget(self.headerFrame)
        self.welcomeWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.welcomeWidget.setObjectName("welcomeWidget")
        self.welcomeLbl = QtWidgets.QLabel(self.welcomeWidget)
        self.welcomeLbl.setGeometry(QtCore.QRect(0, 0, 301, 69))
        self.welcomeLbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLbl.setFont(font)
        self.welcomeLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.welcomeLbl.setObjectName("welcomeLbl")
        self.gridLayout.addWidget(self.welcomeWidget, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.headerFrame)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.accountBtn = QtWidgets.QPushButton(self.widget_3)
        self.accountBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.accountBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.accountBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accountBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/users/images/users/man.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountBtn.setIcon(icon5)
        self.accountBtn.setIconSize(QtCore.QSize(50, 50))
        self.accountBtn.setObjectName("accountBtn")
        self.horizontalLayout_6.addWidget(self.accountBtn, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.widget_3, 0, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.headerFrame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchFrame = QtWidgets.QFrame(self.widget_2)
        self.searchFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.searchFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.searchbtn = QtWidgets.QPushButton(self.searchFrame)
        self.searchbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchbtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/others/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchbtn.setIcon(icon6)
        self.searchbtn.setIconSize(QtCore.QSize(32, 32))
        self.searchbtn.setObjectName("searchbtn")
        self.horizontalLayout_5.addWidget(self.searchbtn, 0, QtCore.Qt.AlignRight)
        self.searchbar = QtWidgets.QLineEdit(self.searchFrame)
        self.searchbar.setObjectName("searchbar")
        self.horizontalLayout_5.addWidget(self.searchbar)
        self.horizontalLayout_4.addWidget(self.searchFrame)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.headerFrame)
        self.mainTabWidget = QtWidgets.QTabWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabWidget.sizePolicy().hasHeightForWidth())
        self.mainTabWidget.setSizePolicy(sizePolicy)
        self.mainTabWidget.setMinimumSize(QtCore.QSize(1000, 0))
        self.mainTabWidget.setAutoFillBackground(False)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.homeTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeTab.sizePolicy().hasHeightForWidth())
        self.homeTab.setSizePolicy(sizePolicy)
        self.homeTab.setObjectName("homeTab")
        self.mainFrame = QtWidgets.QWidget(self.homeTab)
        self.mainFrame.setGeometry(QtCore.QRect(0, 0, 1071, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.mainFrame.setFont(font)
        self.mainFrame.setObjectName("mainFrame")
        self.cardsFrame = QtWidgets.QFrame(self.mainFrame)
        self.cardsFrame.setGeometry(QtCore.QRect(20, 80, 1031, 251))
        self.cardsFrame.setMinimumSize(QtCore.QSize(950, 0))
        self.cardsFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cardsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardsFrame.setObjectName("cardsFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cardsFrame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.card3 = QtWidgets.QWidget(self.cardsFrame)
        self.card3.setMinimumSize(QtCore.QSize(180, 180))
        self.card3.setMaximumSize(QtCore.QSize(180, 180))
        self.card3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.card3.setObjectName("card3")
        self.homePatientsBtn = QtWidgets.QPushButton(self.card3)
        self.homePatientsBtn.setGeometry(QtCore.QRect(10, 40, 160, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(160)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homePatientsBtn.sizePolicy().hasHeightForWidth())
        self.homePatientsBtn.setSizePolicy(sizePolicy)
        self.homePatientsBtn.setMinimumSize(QtCore.QSize(160, 80))
        self.homePatientsBtn.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.homePatientsBtn.setFont(font)
        self.homePatientsBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/others/patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homePatientsBtn.setIcon(icon7)
        self.homePatientsBtn.setIconSize(QtCore.QSize(80, 80))
        self.homePatientsBtn.setObjectName("homePatientsBtn")
        self.label = QtWidgets.QLabel(self.card3)
        self.label.setGeometry(QtCore.QRect(10, 10, 160, 19))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.homePatientsLbl = QtWidgets.QLabel(self.card3)
        self.homePatientsLbl.setGeometry(QtCore.QRect(50, 130, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.homePatientsLbl.setFont(font)
        self.homePatientsLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.homePatientsLbl.setObjectName("homePatientsLbl")
        self.horizontalLayout_7.addWidget(self.card3)
        self.card2 = QtWidgets.QWidget(self.cardsFrame)
        self.card2.setMinimumSize(QtCore.QSize(180, 180))
        self.card2.setMaximumSize(QtCore.QSize(180, 180))
        self.card2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.card2.setObjectName("card2")
        self.homeDoctorsBtn = QtWidgets.QPushButton(self.card2)
        self.homeDoctorsBtn.setGeometry(QtCore.QRect(10, 40, 160, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeDoctorsBtn.sizePolicy().hasHeightForWidth())
        self.homeDoctorsBtn.setSizePolicy(sizePolicy)
        self.homeDoctorsBtn.setMinimumSize(QtCore.QSize(160, 80))
        self.homeDoctorsBtn.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.homeDoctorsBtn.setFont(font)
        self.homeDoctorsBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/others/doctor-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeDoctorsBtn.setIcon(icon8)
        self.homeDoctorsBtn.setIconSize(QtCore.QSize(80, 80))
        self.homeDoctorsBtn.setObjectName("homeDoctorsBtn")
        self.label_2 = QtWidgets.QLabel(self.card2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 160, 19))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.homeDoctorsLbl = QtWidgets.QLabel(self.card2)
        self.homeDoctorsLbl.setGeometry(QtCore.QRect(50, 130, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.homeDoctorsLbl.setFont(font)
        self.homeDoctorsLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.homeDoctorsLbl.setObjectName("homeDoctorsLbl")
        self.horizontalLayout_7.addWidget(self.card2)
        self.card1 = QtWidgets.QWidget(self.cardsFrame)
        self.card1.setMinimumSize(QtCore.QSize(180, 180))
        self.card1.setMaximumSize(QtCore.QSize(180, 180))
        self.card1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.card1.setObjectName("card1")
        self.homeAnalystsBtn = QtWidgets.QPushButton(self.card1)
        self.homeAnalystsBtn.setGeometry(QtCore.QRect(10, 40, 160, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeAnalystsBtn.sizePolicy().hasHeightForWidth())
        self.homeAnalystsBtn.setSizePolicy(sizePolicy)
        self.homeAnalystsBtn.setMinimumSize(QtCore.QSize(160, 80))
        self.homeAnalystsBtn.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.homeAnalystsBtn.setFont(font)
        self.homeAnalystsBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_analyst.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeAnalystsBtn.setIcon(icon9)
        self.homeAnalystsBtn.setIconSize(QtCore.QSize(80, 80))
        self.homeAnalystsBtn.setObjectName("homeAnalystsBtn")
        self.label_6 = QtWidgets.QLabel(self.card1)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 160, 19))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.homeAnalystsLbl = QtWidgets.QLabel(self.card1)
        self.homeAnalystsLbl.setGeometry(QtCore.QRect(50, 130, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.homeAnalystsLbl.setFont(font)
        self.homeAnalystsLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.homeAnalystsLbl.setObjectName("homeAnalystsLbl")
        self.horizontalLayout_7.addWidget(self.card1)
        self.card4 = QtWidgets.QWidget(self.cardsFrame)
        self.card4.setMinimumSize(QtCore.QSize(180, 180))
        self.card4.setMaximumSize(QtCore.QSize(180, 180))
        self.card4.setObjectName("card4")
        self.homeSearchersBtn = QtWidgets.QPushButton(self.card4)
        self.homeSearchersBtn.setGeometry(QtCore.QRect(10, 40, 160, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeSearchersBtn.sizePolicy().hasHeightForWidth())
        self.homeSearchersBtn.setSizePolicy(sizePolicy)
        self.homeSearchersBtn.setMinimumSize(QtCore.QSize(160, 80))
        self.homeSearchersBtn.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.homeSearchersBtn.setFont(font)
        self.homeSearchersBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeSearchersBtn.setIcon(icon10)
        self.homeSearchersBtn.setIconSize(QtCore.QSize(80, 80))
        self.homeSearchersBtn.setObjectName("homeSearchersBtn")
        self.label_9 = QtWidgets.QLabel(self.card4)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 160, 19))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.homeSearchersLbl = QtWidgets.QLabel(self.card4)
        self.homeSearchersLbl.setGeometry(QtCore.QRect(50, 130, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.homeSearchersLbl.setFont(font)
        self.homeSearchersLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.homeSearchersLbl.setObjectName("homeSearchersLbl")
        self.horizontalLayout_7.addWidget(self.card4)
        self.spaceLbl_2 = QtWidgets.QLabel(self.mainFrame)
        self.spaceLbl_2.setGeometry(QtCore.QRect(20, 20, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spaceLbl_2.setFont(font)
        self.spaceLbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spaceLbl_2.setObjectName("spaceLbl_2")
        self.mainTabWidget.addTab(self.homeTab, "")
        self.patientsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patientsTab.sizePolicy().hasHeightForWidth())
        self.patientsTab.setSizePolicy(sizePolicy)
        self.patientsTab.setObjectName("patientsTab")
        self.patientsFrame = QtWidgets.QFrame(self.patientsTab)
        self.patientsFrame.setGeometry(QtCore.QRect(-1, -1, 1071, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patientsFrame.sizePolicy().hasHeightForWidth())
        self.patientsFrame.setSizePolicy(sizePolicy)
        self.patientsFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.patientsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patientsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patientsFrame.setObjectName("patientsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.patientsFrame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usersListTab = QtWidgets.QTabWidget(self.patientsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usersListTab.sizePolicy().hasHeightForWidth())
        self.usersListTab.setSizePolicy(sizePolicy)
        self.usersListTab.setMinimumSize(QtCore.QSize(1050, 0))
        self.usersListTab.setObjectName("usersListTab")
        self.usersTab1 = QtWidgets.QWidget()
        self.usersTab1.setObjectName("usersTab1")
        self.usersWidget = QtWidgets.QWidget(self.usersTab1)
        self.usersWidget.setGeometry(QtCore.QRect(0, 10, 1051, 61))
        self.usersWidget.setObjectName("usersWidget")
        self.usersLabel = QtWidgets.QLabel(self.usersWidget)
        self.usersLabel.setGeometry(QtCore.QRect(9, 9, 661, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.usersLabel.setFont(font)
        self.usersLabel.setObjectName("usersLabel")
        self.addUserBtn = QtWidgets.QPushButton(self.usersWidget)
        self.addUserBtn.setGeometry(QtCore.QRect(690, 10, 110, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addUserBtn.sizePolicy().hasHeightForWidth())
        self.addUserBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.addUserBtn.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addUserBtn.setIcon(icon11)
        self.addUserBtn.setIconSize(QtCore.QSize(35, 35))
        self.addUserBtn.setObjectName("addUserBtn")
        self.deleteUserBtn = QtWidgets.QPushButton(self.usersWidget)
        self.deleteUserBtn.setGeometry(QtCore.QRect(930, 10, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteUserBtn.sizePolicy().hasHeightForWidth())
        self.deleteUserBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.deleteUserBtn.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteUserBtn.setIcon(icon12)
        self.deleteUserBtn.setIconSize(QtCore.QSize(35, 35))
        self.deleteUserBtn.setObjectName("deleteUserBtn")
        self.editUserBtn = QtWidgets.QPushButton(self.usersWidget)
        self.editUserBtn.setGeometry(QtCore.QRect(810, 10, 110, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editUserBtn.sizePolicy().hasHeightForWidth())
        self.editUserBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.editUserBtn.setFont(font)
        self.editUserBtn.setIcon(icon3)
        self.editUserBtn.setIconSize(QtCore.QSize(35, 35))
        self.editUserBtn.setObjectName("editUserBtn")
        self.tableWidget = QtWidgets.QTableWidget(self.usersTab1)
        self.tableWidget.setGeometry(QtCore.QRect(0, 70, 1051, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(1000, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.usersListTab.addTab(self.usersTab1, "")
        self.usersTab2 = QtWidgets.QWidget()
        self.usersTab2.setObjectName("usersTab2")
        self.frame_8 = QtWidgets.QFrame(self.usersTab2)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 981, 591))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.setUserWidget = QtWidgets.QWidget(self.frame_8)
        self.setUserWidget.setGeometry(QtCore.QRect(250, 70, 501, 291))
        self.setUserWidget.setObjectName("setUserWidget")
        self.label_56 = QtWidgets.QLabel(self.setUserWidget)
        self.label_56.setGeometry(QtCore.QRect(60, 40, 211, 31))
        self.label_56.setObjectName("label_56")
        self.label_59 = QtWidgets.QLabel(self.setUserWidget)
        self.label_59.setGeometry(QtCore.QRect(60, 80, 211, 31))
        self.label_59.setObjectName("label_59")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.setUserWidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 80, 201, 27))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.username = QtWidgets.QLineEdit(self.setUserWidget)
        self.username.setEnabled(False)
        self.username.setGeometry(QtCore.QRect(280, 40, 201, 27))
        self.username.setObjectName("username")
        self.saveEditUserBtn = QtWidgets.QPushButton(self.setUserWidget)
        self.saveEditUserBtn.setGeometry(QtCore.QRect(150, 170, 221, 27))
        self.saveEditUserBtn.setObjectName("saveEditUserBtn")
        self.usersListTab.addTab(self.usersTab2, "")
        self.usersTab3 = QtWidgets.QWidget()
        self.usersTab3.setObjectName("usersTab3")
        self.frame_6 = QtWidgets.QFrame(self.usersTab3)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 981, 591))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.addUserWidget = QtWidgets.QWidget(self.frame_6)
        self.addUserWidget.setGeometry(QtCore.QRect(250, 70, 501, 291))
        self.addUserWidget.setObjectName("addUserWidget")
        self.label_35 = QtWidgets.QLabel(self.addUserWidget)
        self.label_35.setGeometry(QtCore.QRect(60, 40, 211, 31))
        self.label_35.setObjectName("label_35")
        self.label_40 = QtWidgets.QLabel(self.addUserWidget)
        self.label_40.setGeometry(QtCore.QRect(60, 80, 211, 31))
        self.label_40.setObjectName("label_40")
        self.label_45 = QtWidgets.QLabel(self.addUserWidget)
        self.label_45.setGeometry(QtCore.QRect(60, 120, 211, 31))
        self.label_45.setObjectName("label_45")
        self.newUserRole = QtWidgets.QComboBox(self.addUserWidget)
        self.newUserRole.setGeometry(QtCore.QRect(280, 120, 201, 27))
        self.newUserRole.setObjectName("newUserRole")
        self.newUserRole.addItem("")
        self.newUserRole.addItem("")
        self.newUserRole.addItem("")
        self.newUserRole.addItem("")
        self.newUserRole.addItem("")
        self.newUserRole.addItem("")
        self.newUserPassword = QtWidgets.QLineEdit(self.addUserWidget)
        self.newUserPassword.setGeometry(QtCore.QRect(280, 80, 201, 27))
        self.newUserPassword.setObjectName("newUserPassword")
        self.newUserUsername = QtWidgets.QLineEdit(self.addUserWidget)
        self.newUserUsername.setGeometry(QtCore.QRect(280, 40, 201, 27))
        self.newUserUsername.setObjectName("newUserUsername")
        self.saveAddUserBtn = QtWidgets.QPushButton(self.addUserWidget)
        self.saveAddUserBtn.setGeometry(QtCore.QRect(150, 200, 221, 27))
        self.saveAddUserBtn.setObjectName("saveAddUserBtn")
        self.usersListTab.addTab(self.usersTab3, "")
        self.usersTab4 = QtWidgets.QWidget()
        self.usersTab4.setObjectName("usersTab4")
        self.frame_9 = QtWidgets.QFrame(self.usersTab4)
        self.frame_9.setGeometry(QtCore.QRect(280, 180, 541, 129))
        self.frame_9.setMinimumSize(QtCore.QSize(500, 120))
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.verticalLayout_18.addWidget(self.frame_10)
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.deleteUserBtnNo = QtWidgets.QPushButton(self.frame_13)
        self.deleteUserBtnNo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteUserBtnNo.setObjectName("deleteUserBtnNo")
        self.horizontalLayout_11.addWidget(self.deleteUserBtnNo)
        self.deleteUserBtnYes = QtWidgets.QPushButton(self.frame_13)
        self.deleteUserBtnYes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteUserBtnYes.setObjectName("deleteUserBtnYes")
        self.horizontalLayout_11.addWidget(self.deleteUserBtnYes)
        self.verticalLayout_18.addWidget(self.frame_13)
        self.usersListTab.addTab(self.usersTab4, "")
        self.verticalLayout_2.addWidget(self.usersListTab)
        self.mainTabWidget.addTab(self.patientsTab, "")
        self.documentsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentsTab.sizePolicy().hasHeightForWidth())
        self.documentsTab.setSizePolicy(sizePolicy)
        self.documentsTab.setObjectName("documentsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.documentsTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.documentsFrame = QtWidgets.QFrame(self.documentsTab)
        self.documentsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.documentsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.documentsFrame.setObjectName("documentsFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.documentsFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.documentsFrame)
        self.widget_4.setMinimumSize(QtCore.QSize(700, 200))
        self.widget_4.setObjectName("widget_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 711, 161))
        self.label_4.setMinimumSize(QtCore.QSize(450, 150))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.widget_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.documentsFrame)
        self.mainTabWidget.addTab(self.documentsTab, "")
        self.privacyTab = QtWidgets.QWidget()
        self.privacyTab.setObjectName("privacyTab")
        self.privacyFrame = QtWidgets.QFrame(self.privacyTab)
        self.privacyFrame.setGeometry(QtCore.QRect(0, 0, 1011, 471))
        self.privacyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.privacyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.privacyFrame.setObjectName("privacyFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.privacyFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.privacyFrame)
        self.widget_5.setMinimumSize(QtCore.QSize(700, 200))
        self.widget_5.setObjectName("widget_5")
        self.label_27 = QtWidgets.QLabel(self.widget_5)
        self.label_27.setGeometry(QtCore.QRect(160, 110, 711, 100))
        self.label_27.setMinimumSize(QtCore.QSize(450, 100))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.privacySlider = QtWidgets.QSlider(self.widget_5)
        self.privacySlider.setGeometry(QtCore.QRect(380, 230, 271, 16))
        self.privacySlider.setMaximum(100)
        self.privacySlider.setSingleStep(25)
        self.privacySlider.setPageStep(25)
        self.privacySlider.setOrientation(QtCore.Qt.Horizontal)
        self.privacySlider.setObjectName("privacySlider")
        self.savePrivacyBtn = QtWidgets.QPushButton(self.widget_5)
        self.savePrivacyBtn.setGeometry(QtCore.QRect(460, 310, 131, 27))
        self.savePrivacyBtn.setObjectName("savePrivacyBtn")
        self.epsilon_lbl = QtWidgets.QLabel(self.widget_5)
        self.epsilon_lbl.setGeometry(QtCore.QRect(436, 190, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.epsilon_lbl.setFont(font)
        self.epsilon_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.epsilon_lbl.setObjectName("epsilon_lbl")
        self.verticalLayout_5.addWidget(self.widget_5)
        self.mainTabWidget.addTab(self.privacyTab, "")
        self.accountTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountTab.sizePolicy().hasHeightForWidth())
        self.accountTab.setSizePolicy(sizePolicy)
        self.accountTab.setMinimumSize(QtCore.QSize(1000, 0))
        self.accountTab.setObjectName("accountTab")
        self.frame_7 = QtWidgets.QFrame(self.accountTab)
        self.frame_7.setGeometry(QtCore.QRect(20, 10, 1021, 4000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 4000))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 4000))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.accountHomeBtn = QtWidgets.QFrame(self.frame_7)
        self.accountHomeBtn.setGeometry(QtCore.QRect(0, 10, 1001, 136))
        self.accountHomeBtn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountHomeBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountHomeBtn.setObjectName("accountHomeBtn")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.accountHomeBtn)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_27 = QtWidgets.QWidget(self.accountHomeBtn)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.infoHomeBtn = QtWidgets.QPushButton(self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.infoHomeBtn.setFont(font)
        self.infoHomeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoHomeBtn.setIcon(icon13)
        self.infoHomeBtn.setIconSize(QtCore.QSize(100, 100))
        self.infoHomeBtn.setObjectName("infoHomeBtn")
        self.horizontalLayout_9.addWidget(self.infoHomeBtn)
        self.horizontalLayout_14.addWidget(self.widget_27)
        self.accountFrame = QtWidgets.QFrame(self.frame_7)
        self.accountFrame.setGeometry(QtCore.QRect(0, 170, 1001, 411))
        self.accountFrame.setMinimumSize(QtCore.QSize(0, 400))
        self.accountFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountFrame.setObjectName("accountFrame")
        self.scrollArea = QtWidgets.QScrollArea(self.accountFrame)
        self.scrollArea.setGeometry(QtCore.QRect(-1, 0, 1001, 401))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 400))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 993, 4000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 4000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.accountInfoFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.accountInfoFrame.setGeometry(QtCore.QRect(1, 9, 990, 3991))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountInfoFrame.sizePolicy().hasHeightForWidth())
        self.accountInfoFrame.setSizePolicy(sizePolicy)
        self.accountInfoFrame.setMinimumSize(QtCore.QSize(990, 1000))
        self.accountInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountInfoFrame.setObjectName("accountInfoFrame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.accountInfoFrame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.infoFrame = QtWidgets.QFrame(self.accountInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoFrame.sizePolicy().hasHeightForWidth())
        self.infoFrame.setSizePolicy(sizePolicy)
        self.infoFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.infoFrame)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.infoContentFrame = QtWidgets.QFrame(self.infoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoContentFrame.sizePolicy().hasHeightForWidth())
        self.infoContentFrame.setSizePolicy(sizePolicy)
        self.infoContentFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.infoContentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoContentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoContentFrame.setObjectName("infoContentFrame")
        self.frame_11 = QtWidgets.QFrame(self.infoContentFrame)
        self.frame_11.setGeometry(QtCore.QRect(260, 30, 211, 251))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 67, 19))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setGeometry(QtCore.QRect(10, 88, 201, 21))
        self.label_16.setObjectName("label_16")
        self.label_25 = QtWidgets.QLabel(self.frame_11)
        self.label_25.setGeometry(QtCore.QRect(10, 150, 201, 19))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_11)
        self.label_26.setGeometry(QtCore.QRect(10, 200, 201, 31))
        self.label_26.setObjectName("label_26")
        self.frame_12 = QtWidgets.QFrame(self.infoContentFrame)
        self.frame_12.setGeometry(QtCore.QRect(470, 20, 261, 331))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.nom = QtWidgets.QLineEdit(self.frame_12)
        self.nom.setObjectName("nom")
        self.verticalLayout_29.addWidget(self.nom)
        self.prenom = QtWidgets.QLineEdit(self.frame_12)
        self.prenom.setObjectName("prenom")
        self.verticalLayout_29.addWidget(self.prenom)
        self.username_2 = QtWidgets.QLineEdit(self.frame_12)
        self.username_2.setEnabled(False)
        self.username_2.setObjectName("username_2")
        self.verticalLayout_29.addWidget(self.username_2)
        self.password = QtWidgets.QLineEdit(self.frame_12)
        self.password.setObjectName("password")
        self.verticalLayout_29.addWidget(self.password)
        self.email = QtWidgets.QLineEdit(self.frame_12)
        self.email.setObjectName("email")
        self.verticalLayout_29.addWidget(self.email)
        self.infoContentSaveBtn = QtWidgets.QPushButton(self.infoContentFrame)
        self.infoContentSaveBtn.setGeometry(QtCore.QRect(400, 340, 181, 39))
        self.infoContentSaveBtn.setObjectName("infoContentSaveBtn")
        self.label_28 = QtWidgets.QLabel(self.infoContentFrame)
        self.label_28.setGeometry(QtCore.QRect(270, 290, 201, 31))
        self.label_28.setObjectName("label_28")
        self.verticalLayout_26.addWidget(self.infoContentFrame)
        self.verticalLayout_21.addWidget(self.infoFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainTabWidget.addTab(self.accountTab, "")
        self.logoutTab = QtWidgets.QWidget()
        self.logoutTab.setObjectName("logoutTab")
        self.logoutTabFrame = QtWidgets.QFrame(self.logoutTab)
        self.logoutTabFrame.setGeometry(QtCore.QRect(10, 0, 1001, 641))
        self.logoutTabFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoutTabFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoutTabFrame.setObjectName("logoutTabFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.logoutTabFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_5 = QtWidgets.QFrame(self.logoutTabFrame)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 120))
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_17.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoutBtnNo = QtWidgets.QPushButton(self.frame_4)
        self.logoutBtnNo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutBtnNo.setObjectName("logoutBtnNo")
        self.horizontalLayout_2.addWidget(self.logoutBtnNo)
        self.logoutBtnYes = QtWidgets.QPushButton(self.frame_4)
        self.logoutBtnYes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutBtnYes.setObjectName("logoutBtnYes")
        self.horizontalLayout_2.addWidget(self.logoutBtnYes)
        self.verticalLayout_17.addWidget(self.frame_4)
        self.verticalLayout_12.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mainTabWidget.addTab(self.logoutTab, "")
        self.verticalLayout.addWidget(self.mainTabWidget)
        self.horizontalLayout.addWidget(self.mainBody)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.mainTabWidget.setCurrentIndex(1)
        self.usersListTab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Espace admin"))
        self.logoLbl.setText(_translate("mainWindow", "COVID 19"))
        self.homeBtn.setText(_translate("mainWindow", "  Accueil"))
        self.usersBtn.setText(_translate("mainWindow", " Utilisateurs"))
        self.privacyBtn.setText(_translate("mainWindow", " Confidentialité"))
        self.accountLeftBtn.setText(_translate("mainWindow", " Compte"))
        self.logoutBtn.setText(_translate("mainWindow", "Se déconnecter"))
        self.spaceLbl.setText(_translate("mainWindow", "Espace admin"))
        self.welcomeLbl.setText(_translate("mainWindow", "Bienvenue admin1!"))
        self.searchbar.setPlaceholderText(_translate("mainWindow", "Rechercher"))
        self.label.setText(_translate("mainWindow", "Patients"))
        self.homePatientsLbl.setText(_translate("mainWindow", "10"))
        self.label_2.setText(_translate("mainWindow", "Medecins"))
        self.homeDoctorsLbl.setText(_translate("mainWindow", "2"))
        self.label_6.setText(_translate("mainWindow", "Analystes"))
        self.homeAnalystsLbl.setText(_translate("mainWindow", "1"))
        self.label_9.setText(_translate("mainWindow", "Chercheurs"))
        self.homeSearchersLbl.setText(_translate("mainWindow", "1"))
        self.spaceLbl_2.setText(_translate("mainWindow", "Statistiques utilisateurs:"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.homeTab), _translate("mainWindow", "Acceuil"))
        self.usersLabel.setText(_translate("mainWindow", "Patients"))
        self.addUserBtn.setText(_translate("mainWindow", " Ajouter"))
        self.deleteUserBtn.setText(_translate("mainWindow", "Supprimer"))
        self.editUserBtn.setText(_translate("mainWindow", "Modifier"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Utilisateur"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Prénom"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Date d\'inscription"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Rôle"))
        self.usersListTab.setTabText(self.usersListTab.indexOf(self.usersTab1), _translate("mainWindow", "Table"))
        self.label_56.setText(_translate("mainWindow", "Nom utilisateur:"))
        self.label_59.setText(_translate("mainWindow", "Mot de passe:"))
        self.lineEdit_4.setText(_translate("mainWindow", "*******"))
        self.username.setText(_translate("mainWindow", "nabil"))
        self.saveEditUserBtn.setText(_translate("mainWindow", "Enregistrer"))
        self.usersListTab.setTabText(self.usersListTab.indexOf(self.usersTab2), _translate("mainWindow", "Modifier"))
        self.label_35.setText(_translate("mainWindow", "Nom utilisateur:"))
        self.label_40.setText(_translate("mainWindow", "Mot de passe:"))
        self.label_45.setText(_translate("mainWindow", "Role:"))
        self.newUserRole.setItemText(0, _translate("mainWindow", "Admin"))
        self.newUserRole.setItemText(1, _translate("mainWindow", "Medecin"))
        self.newUserRole.setItemText(2, _translate("mainWindow", "Patient"))
        self.newUserRole.setItemText(3, _translate("mainWindow", "Analyste"))
        self.newUserRole.setItemText(4, _translate("mainWindow", "Chercheur"))
        self.newUserRole.setItemText(5, _translate("mainWindow", "Pharmacien"))
        self.saveAddUserBtn.setText(_translate("mainWindow", "Ajouter l\'utilisateur"))
        self.usersListTab.setTabText(self.usersListTab.indexOf(self.usersTab3), _translate("mainWindow", "Ajouter"))
        self.label_7.setText(_translate("mainWindow", "Voulez-vous vraiment supprimer l\'utilisateur?"))
        self.deleteUserBtnNo.setText(_translate("mainWindow", "Non"))
        self.deleteUserBtnYes.setText(_translate("mainWindow", "Oui"))
        self.usersListTab.setTabText(self.usersListTab.indexOf(self.usersTab4), _translate("mainWindow", "Supprimer"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.patientsTab), _translate("mainWindow", "Utilisateurs"))
        self.label_4.setText(_translate("mainWindow", "Vous n’avez aucun document disponible"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.documentsTab), _translate("mainWindow", "Documents"))
        self.label_27.setText(_translate("mainWindow", "Niveau de confidentialité :"))
        self.savePrivacyBtn.setText(_translate("mainWindow", "Sauvegarder"))
        self.epsilon_lbl.setText(_translate("mainWindow", "Epsilon = 1"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.privacyTab), _translate("mainWindow", "Confidentialité"))
        self.infoHomeBtn.setText(_translate("mainWindow", " Mes informations"))
        self.label_15.setText(_translate("mainWindow", "Nom :"))
        self.label_16.setText(_translate("mainWindow", "Prénom :"))
        self.label_25.setText(_translate("mainWindow", "Now utilisateur"))
        self.label_26.setText(_translate("mainWindow", "Mot de passe:"))
        self.nom.setText(_translate("mainWindow", "Med"))
        self.nom.setPlaceholderText(_translate("mainWindow", "Prénom"))
        self.prenom.setText(_translate("mainWindow", "Ben"))
        self.prenom.setPlaceholderText(_translate("mainWindow", "Nom"))
        self.username_2.setText(_translate("mainWindow", "med_ben"))
        self.username_2.setPlaceholderText(_translate("mainWindow", "Téléphone"))
        self.password.setText(_translate("mainWindow", "********"))
        self.password.setPlaceholderText(_translate("mainWindow", "Adresse e-mail"))
        self.infoContentSaveBtn.setText(_translate("mainWindow", "Sauvegarder"))
        self.label_28.setText(_translate("mainWindow", "Email"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.accountTab), _translate("mainWindow", "Compte"))
        self.label_5.setText(_translate("mainWindow", "Voulez-vous vraiment se déconnecter?"))
        self.logoutBtnNo.setText(_translate("mainWindow", "Non"))
        self.logoutBtnYes.setText(_translate("mainWindow", "Oui"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.logoutTab), _translate("mainWindow", "Se déconnecter"))
import resource_rc
