# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1300, 755)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1300, 650))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        mainWindow.setFont(font)
        mainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("* {\n"
"    color: #343542;\n"
"    border: none;\n"
"}\n"
"\n"
"#leftMenuFrame {\n"
"    background-image: url(\":/images/images/sideLeft.png\");\n"
"    color: #eff9fe;\n"
"}\n"
"\n"
" #mainBody {\n"
"    background-image: url(\":/images/images/main.png\");\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"#homeTab, #consultingTab, #documentsTab, #accountTab, #logoutTab, #patientsTab, #patientsListTab, #patientsListTab1, #patientsListTab2 {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#accountFrame, #scrollArea, #scrollAreaWidgetContents, #scrollArea_2, #scrollAreaWidgetContents_2, #scrollArea_3, #scrollAreaWidgetContents_3 {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#patientsDettalLabel  {\n"
"    border: 2px solid #C4C4C3;\n"
"    background: #EEF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QTableView {\n"
"    border: 1px solid #222;\n"
"    padding: 0px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 14px;\n"
"    background-color: #EEF;\n"
"    alternate-background-color: #424242;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #3388ff;\n"
"}\n"
"QTableView QTableCornerButton::section {\n"
"    background-color: #292929;\n"
"    border: 1px;\n"
"    padding: 0px\n"
"}\n"
"QHeaderView, QHeaderView::section {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    font-size: 15px;\n"
"    border: 1px solid #C4C4C3;\n"
"    padding: 0px\n"
"}\n"
"\n"
"#patientsTable, #patientsDettalsTable {\n"
"    border-top: 2px solid #C4C4C3;\n"
"    border-left: 2px solid #C4C4C3;\n"
"    background: #EEF;\n"
"}\n"
"\n"
"#patientsTable QWidget, #patientsDettalsTable QWidget , #patientsDettalsTable QWidget {\n"
"    border-right: 2px solid #C4C4C3;\n"
"    border-bottom: 2px solid #C4C4C3;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: transparent;\n"
"    color: #343542;\n"
"}\n"
"\n"
"QPlainTextEdit  {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #343542;\n"
"    border: 1px solid #9B9B9B ;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox , QDateEdit {\n"
"    background-color: #F9F8FC;\n"
"    padding: 5px;\n"
"    border: 1px solid #343542;\n"
"}\n"
"\n"
"#headerFrame {\n"
"    background-color: #F9F8FC;\n"
"}\n"
"\n"
"#searchFrame {\n"
"    background-color: #fefeff;\n"
"    border-radius: 20px;\n"
"    border: 2px solid #343542;\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"#accountBtn {\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#welcomeLbl {\n"
"    text-align: right;\n"
"}\n"
"\n"
"#card1, #card2, #card3, #card4, #card5, #card6  {\n"
"        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ebeff7, stop: 0.5 #c6d5ff, stop: 1 #afd1f4);\n"
"    border-radius: 20px;\n"
"    border: 2px solid #2596be;\n"
"}\n"
"\n"
"#card1icon, #card2icon, #card3icon, #card4icon, #card5icon, #card6icon  {\n"
"    border: 3px solid #343542;\n"
"    padding-top: 15px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    padding-bottom: 45px;\n"
"    border-radius: 60px;\n"
"}\n"
"\n"
"#card1btn:hover, #card2btn:hover, #card3btn:hover, #card4btn:hover, #card5btn:hover, #card6btn:hover  {\n"
"    margin-left: 15px;\n"
"}\n"
"\n"
"\n"
"#aside {\n"
"    background-color: #fefeff;\n"
"    border-radius: 15px;\n"
"    margin-top: 15px;\n"
"}\n"
"\n"
"QPushButton#homeBtn, #consultingBtn, #documentsBtn, #accountLeftBtn, #logoutBtn{\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"#asideBtn {\n"
"    border-radius: 20px;\n"
"    border: 2px solid #2596be;\n"
"    padding: 6px;\n"
"    color: #2596be;\n"
"}\n"
"\n"
"#asideBtn:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #eff9fe;\n"
"}\n"
"\n"
"QPushButton#homeBtn,#consultingBtn, #documentsBtn, #accountLeftBtn, #logoutBtn, #logoLbl {\n"
"    color: #EFF9FE;\n"
"}\n"
"\n"
"#welcomeLbl, #spaceLbl {\n"
"    color: #343542;\n"
"}\n"
"\n"
"QPushButton#homeBtn:hover, #consultingBtn:hover, #documentsBtn:hover, #accountLeftBtn:hover, #logoutBtn:hover{    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    border-top-left-radius: 15px;\n"
"    color: #EFF9FE;\n"
"}\n"
"\n"
"QPushButton#homeBtn:selected, #consultingBtn:selected, #documentsBtn:selected, #accountLeftBtn:selected, #logoutBtn:selected{    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #eff9fe;\n"
"    border-top-left-radius: 15px;\n"
"}\n"
"\n"
"#medicalLbl, #infoLbl {    \n"
"    color: #343542;\n"
"}\n"
"\n"
"#medicalFrame, #infoFrame, #accountInfoFrame, #medicalContentTab2, #medicalContentTab3, #medicalContentTab4, #medicalContentTab5, #accountInfoContents, #accountInfoScrollArea, #accountInfoTab {    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#infoFrame QLineEdit, #medicalFrame QLineEdit,\n"
"#infoFrame QComboBox, #medicalFrame QComboBox ,\n"
"#infoFrame QDateEdit, #medicalFrame QDateEdit {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #343542;\n"
"    border: 1px solid #9B9B9B ;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#Frame QComboBox:selected, \n"
"#medicalFrame QComboBox:selected  {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #343542;\n"
"    border: 1px solid #9B9B9B ;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#accountContents {\n"
"    background: #F9F8FC;\n"
"}\n"
"\n"
"Line {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"\n"
"#pushButton_8,#pushButton_9, #pushButton_10, #pushButton_11, #pushButton_12  , #infoContentSaveBtn, #logoutBtnYes, #logoutBtnNo{\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    padding: 10px;\n"
"    color: #eff9fe;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#pushButton_8:hover,#pushButton_9:hover, #pushButton_10:hover, #pushButton_11:hover, #pushButton_12:hover, #infoContentSaveBtn:hover, #logoutBtnYes:hover, #logoutBtnNo:hover {\n"
"    background-color: #2580be;\n"
"}\n"
"\n"
"#infoHomeBtn, #medicalHomeBtn, #medicalBtn QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color: #003542;\n"
"    border-radius: 20px;\n"
"    border: 2px solid #2596be;\n"
"}\n"
"\n"
"#infoHomeBtn:hover, #medicalHomeBtn:hover, #medicalBtn QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fefefe, stop: 0.4 #f8f8f8, stop: 0.5 #eaeaea, stop: 1.0 #fefefe);    \n"
"    color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    border-radius: 50px;\n"
"}\n"
"\n"
"#medicalContentLayout {\n"
"    background-color: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#medicalContentTab1 {    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#accountFrame {\n"
"    border: 2px solid #C2C7CB;\n"
"}\n"
"/***********************************************************/\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"border-top: 2px solid #C2C7CB;\n"
"background-color: transparent;\n"
"}\n"
"#mainTabWidget::tab-bar {\n"
"width: 1000px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"border: 2px solid #C4C4C3;\n"
"border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"min-width: 8ex;\n"
"padding: 2px;\n"
"color: #eff9fe;\n"
"height: 20px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"color: #343542;\n"
"}\n"
"QTabBar::tab:selected {\n"
"color: #343542;\n"
"border-color: #9B9B9B;\n"
"border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"QTabBar::tab:!selected {\n"
"margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"/* IMPORTANT: 8< Add the code above here 8< */\n"
"QTabBar::tab:selected {\n"
"/* expand/overlap to the left and right by 4px */\n"
"margin-left: -4px;\n"
"margin-right: -4px;\n"
"}\n"
"QTabBar::tab:first:selected {\n"
"margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"}\n"
"QTabBar::tab:last:selected {\n"
"margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"QTabBar::tab:only-one {\n"
"margin: 0; /* if there is only one tab, we don\'t want overlapping margins */\n"
"}\n"
"/***********************************************************/\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #2576be;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: #2576be;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: #2576be;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/***********************************************************/\n"
"\n"
"QCheckBox {\n"
"    color: #343542;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-color: #9B9B9B;\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    padding-bottom: 2px;\n"
"    padding-top: 2px;\n"
"    border-width:1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    color: #2586be;\n"
"        border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #343542;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #343542;\n"
"    background-color:transparent;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: #9B9B9B;\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    padding-bottom: 2px;\n"
"    padding-top: 2px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #343542;\n"
"        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    font-weight: bold;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2596be, stop: 0.4 #2586be, stop: 0.5 #2576be, stop: 1.0 #2566be);\n"
"    color: #343542;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenu.sizePolicy().hasHeightForWidth())
        self.leftMenu.setSizePolicy(sizePolicy)
        self.leftMenu.setMinimumSize(QtCore.QSize(220, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(220, 16777215))
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenuFrame.sizePolicy().hasHeightForWidth())
        self.leftMenuFrame.setSizePolicy(sizePolicy)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalLayout_7.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.leftMenuFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.logoLbl = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logoLbl.setFont(font)
        self.logoLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLbl.setObjectName("logoLbl")
        self.horizontalLayout_8.addWidget(self.logoLbl)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.leftBtnFrame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBtnFrame.sizePolicy().hasHeightForWidth())
        self.leftBtnFrame.setSizePolicy(sizePolicy)
        self.leftBtnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBtnFrame.setObjectName("leftBtnFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.leftBtnFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.homeBtn = QtWidgets.QPushButton(self.leftBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.homeBtn.setFont(font)
        self.homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/others/home-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setIconSize(QtCore.QSize(50, 50))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_8.addWidget(self.homeBtn)
        self.consultingBtn = QtWidgets.QPushButton(self.leftBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.consultingBtn.setFont(font)
        self.consultingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/others/patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consultingBtn.setIcon(icon1)
        self.consultingBtn.setIconSize(QtCore.QSize(50, 50))
        self.consultingBtn.setObjectName("consultingBtn")
        self.verticalLayout_8.addWidget(self.consultingBtn)
        self.accountLeftBtn = QtWidgets.QPushButton(self.leftBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.accountLeftBtn.setFont(font)
        self.accountLeftBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_edit-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountLeftBtn.setIcon(icon2)
        self.accountLeftBtn.setIconSize(QtCore.QSize(50, 50))
        self.accountLeftBtn.setObjectName("accountLeftBtn")
        self.verticalLayout_8.addWidget(self.accountLeftBtn)
        self.verticalLayout_9.addWidget(self.leftBtnFrame, 0, QtCore.Qt.AlignTop)
        self.logoutFrame = QtWidgets.QFrame(self.frame_3)
        self.logoutFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoutFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoutFrame.setObjectName("logoutFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.logoutFrame)
        self.verticalLayout_10.setContentsMargins(0, 0, 2, 9)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.logoutBtn = QtWidgets.QPushButton(self.logoutFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.logoutBtn.setFont(font)
        self.logoutBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/others/exit-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutBtn.setIcon(icon3)
        self.logoutBtn.setIconSize(QtCore.QSize(50, 50))
        self.logoutBtn.setCheckable(False)
        self.logoutBtn.setChecked(False)
        self.logoutBtn.setObjectName("logoutBtn")
        self.verticalLayout_10.addWidget(self.logoutBtn)
        self.verticalLayout_9.addWidget(self.logoutFrame, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.verticalLayout_6.addWidget(self.leftMenuFrame)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerFrame.sizePolicy().hasHeightForWidth())
        self.headerFrame.setSizePolicy(sizePolicy)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.headerFrame.setObjectName("headerFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.headerFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spaceWidget = QtWidgets.QWidget(self.headerFrame)
        self.spaceWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.spaceWidget.setObjectName("spaceWidget")
        self.spaceLbl = QtWidgets.QLabel(self.spaceWidget)
        self.spaceLbl.setGeometry(QtCore.QRect(0, 0, 201, 69))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spaceLbl.setFont(font)
        self.spaceLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.spaceLbl.setObjectName("spaceLbl")
        self.gridLayout.addWidget(self.spaceWidget, 0, 0, 1, 1)
        self.welcomeWidget = QtWidgets.QWidget(self.headerFrame)
        self.welcomeWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.welcomeWidget.setObjectName("welcomeWidget")
        self.welcomeLbl = QtWidgets.QLabel(self.welcomeWidget)
        self.welcomeLbl.setGeometry(QtCore.QRect(0, 0, 301, 69))
        self.welcomeLbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLbl.setFont(font)
        self.welcomeLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.welcomeLbl.setObjectName("welcomeLbl")
        self.gridLayout.addWidget(self.welcomeWidget, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.headerFrame)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.accountBtn = QtWidgets.QPushButton(self.widget_3)
        self.accountBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.accountBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.accountBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accountBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconsBlue/icons/blue_2596be/contacts-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountBtn.setIcon(icon4)
        self.accountBtn.setIconSize(QtCore.QSize(50, 50))
        self.accountBtn.setObjectName("accountBtn")
        self.horizontalLayout_6.addWidget(self.accountBtn, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.widget_3, 0, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.headerFrame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchFrame = QtWidgets.QFrame(self.widget_2)
        self.searchFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.searchFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.searchbtn = QtWidgets.QPushButton(self.searchFrame)
        self.searchbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchbtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/others/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchbtn.setIcon(icon5)
        self.searchbtn.setIconSize(QtCore.QSize(32, 32))
        self.searchbtn.setObjectName("searchbtn")
        self.horizontalLayout_5.addWidget(self.searchbtn, 0, QtCore.Qt.AlignRight)
        self.searchbar = QtWidgets.QLineEdit(self.searchFrame)
        self.searchbar.setObjectName("searchbar")
        self.horizontalLayout_5.addWidget(self.searchbar)
        self.horizontalLayout_4.addWidget(self.searchFrame)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.headerFrame)
        self.mainTabWidget = QtWidgets.QTabWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabWidget.sizePolicy().hasHeightForWidth())
        self.mainTabWidget.setSizePolicy(sizePolicy)
        self.mainTabWidget.setMinimumSize(QtCore.QSize(1200, 0))
        self.mainTabWidget.setAutoFillBackground(False)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.homeTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeTab.sizePolicy().hasHeightForWidth())
        self.homeTab.setSizePolicy(sizePolicy)
        self.homeTab.setObjectName("homeTab")
        self.mainFrame = QtWidgets.QWidget(self.homeTab)
        self.mainFrame.setGeometry(QtCore.QRect(0, 0, 1081, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setObjectName("mainFrame")
        self.homePatientsLbl = QtWidgets.QLabel(self.mainFrame)
        self.homePatientsLbl.setGeometry(QtCore.QRect(20, 20, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.homePatientsLbl.setFont(font)
        self.homePatientsLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.homePatientsLbl.setObjectName("homePatientsLbl")
        self.tabWidget = QtWidgets.QTabWidget(self.mainFrame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 80, 1071, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.cardsFrame = QtWidgets.QFrame(self.tab)
        self.cardsFrame.setGeometry(QtCore.QRect(0, 0, 1000, 521))
        self.cardsFrame.setMinimumSize(QtCore.QSize(1000, 0))
        self.cardsFrame.setMaximumSize(QtCore.QSize(1000, 550))
        self.cardsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardsFrame.setObjectName("cardsFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.cardsFrame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.card3 = QtWidgets.QWidget(self.cardsFrame)
        self.card3.setMinimumSize(QtCore.QSize(250, 250))
        self.card3.setMaximumSize(QtCore.QSize(250, 250))
        self.card3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.card3.setObjectName("card3")
        self.card3icon = QtWidgets.QLabel(self.card3)
        self.card3icon.setGeometry(QtCore.QRect(40, 25, 170, 150))
        self.card3icon.setMinimumSize(QtCore.QSize(0, 0))
        self.card3icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.card3icon.setText("")
        self.card3icon.setScaledContents(True)
        self.card3icon.setObjectName("card3icon")
        self.label_24 = QtWidgets.QLabel(self.card3)
        self.label_24.setGeometry(QtCore.QRect(90, 130, 67, 19))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.totalTestsLbl = QtWidgets.QLabel(self.card3)
        self.totalTestsLbl.setGeometry(QtCore.QRect(30, 210, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalTestsLbl.setFont(font)
        self.totalTestsLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTestsLbl.setObjectName("totalTestsLbl")
        self.card1btn = QtWidgets.QPushButton(self.card3)
        self.card1btn.setGeometry(QtCore.QRect(40, 26, 171, 111))
        self.card1btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconCovid/icons/covid/blood-sample (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card1btn.setIcon(icon6)
        self.card1btn.setIconSize(QtCore.QSize(100, 100))
        self.card1btn.setObjectName("card1btn")
        self.gridLayout_3.addWidget(self.card3, 0, 0, 1, 1)
        self.card1 = QtWidgets.QWidget(self.cardsFrame)
        self.card1.setMinimumSize(QtCore.QSize(250, 250))
        self.card1.setMaximumSize(QtCore.QSize(250, 250))
        self.card1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.card1.setObjectName("card1")
        self.label_33 = QtWidgets.QLabel(self.card1)
        self.label_33.setGeometry(QtCore.QRect(180, 50, 100, 100))
        self.label_33.setMinimumSize(QtCore.QSize(100, 100))
        self.label_33.setMaximumSize(QtCore.QSize(100, 100))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap(":/icons/assets/icons/others/preferences.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.card1icon = QtWidgets.QLabel(self.card1)
        self.card1icon.setGeometry(QtCore.QRect(40, 25, 170, 150))
        self.card1icon.setText("")
        self.card1icon.setScaledContents(True)
        self.card1icon.setObjectName("card1icon")
        self.label_34 = QtWidgets.QLabel(self.card1)
        self.label_34.setGeometry(QtCore.QRect(76, 130, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.totalActivesLbl = QtWidgets.QLabel(self.card1)
        self.totalActivesLbl.setGeometry(QtCore.QRect(30, 210, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalActivesLbl.setFont(font)
        self.totalActivesLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.totalActivesLbl.setObjectName("totalActivesLbl")
        self.card3btn = QtWidgets.QPushButton(self.card1)
        self.card3btn.setGeometry(QtCore.QRect(40, 26, 171, 111))
        self.card3btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconCovid/icons/covid/patient (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card3btn.setIcon(icon7)
        self.card3btn.setIconSize(QtCore.QSize(100, 100))
        self.card3btn.setObjectName("card3btn")
        self.gridLayout_3.addWidget(self.card1, 0, 2, 1, 1)
        self.card6 = QtWidgets.QWidget(self.cardsFrame)
        self.card6.setMinimumSize(QtCore.QSize(250, 250))
        self.card6.setMaximumSize(QtCore.QSize(250, 250))
        self.card6.setObjectName("card6")
        self.card6icon = QtWidgets.QLabel(self.card6)
        self.card6icon.setGeometry(QtCore.QRect(40, 25, 170, 150))
        self.card6icon.setText("")
        self.card6icon.setScaledContents(True)
        self.card6icon.setObjectName("card6icon")
        self.label_37 = QtWidgets.QLabel(self.card6)
        self.label_37.setGeometry(QtCore.QRect(80, 130, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.totalDeathsLbl = QtWidgets.QLabel(self.card6)
        self.totalDeathsLbl.setGeometry(QtCore.QRect(30, 210, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalDeathsLbl.setFont(font)
        self.totalDeathsLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDeathsLbl.setObjectName("totalDeathsLbl")
        self.card5btn = QtWidgets.QPushButton(self.card6)
        self.card5btn.setGeometry(QtCore.QRect(40, 26, 171, 111))
        self.card5btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/iconCovid/icons/covid/death (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card5btn.setIcon(icon8)
        self.card5btn.setIconSize(QtCore.QSize(100, 100))
        self.card5btn.setObjectName("card5btn")
        self.gridLayout_3.addWidget(self.card6, 1, 1, 1, 1)
        self.card4 = QtWidgets.QWidget(self.cardsFrame)
        self.card4.setMinimumSize(QtCore.QSize(250, 250))
        self.card4.setMaximumSize(QtCore.QSize(250, 250))
        self.card4.setObjectName("card4")
        self.card4icon = QtWidgets.QLabel(self.card4)
        self.card4icon.setGeometry(QtCore.QRect(40, 25, 170, 150))
        self.card4icon.setText("")
        self.card4icon.setScaledContents(True)
        self.card4icon.setObjectName("card4icon")
        self.label_40 = QtWidgets.QLabel(self.card4)
        self.label_40.setGeometry(QtCore.QRect(50, 130, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.totalDosesLbl = QtWidgets.QLabel(self.card4)
        self.totalDosesLbl.setGeometry(QtCore.QRect(30, 210, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalDosesLbl.setFont(font)
        self.totalDosesLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDosesLbl.setObjectName("totalDosesLbl")
        self.card6btn = QtWidgets.QPushButton(self.card4)
        self.card6btn.setGeometry(QtCore.QRect(40, 26, 171, 111))
        self.card6btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/iconCovid/icons/covid/vaccine (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card6btn.setIcon(icon9)
        self.card6btn.setIconSize(QtCore.QSize(100, 100))
        self.card6btn.setObjectName("card6btn")
        self.gridLayout_3.addWidget(self.card4, 1, 2, 1, 1)
        self.card2 = QtWidgets.QWidget(self.cardsFrame)
        self.card2.setMinimumSize(QtCore.QSize(250, 250))
        self.card2.setMaximumSize(QtCore.QSize(250, 250))
        self.card2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.card2.setObjectName("card2")
        self.card2icon = QtWidgets.QLabel(self.card2)
        self.card2icon.setGeometry(QtCore.QRect(40, 25, 170, 150))
        self.card2icon.setText("")
        self.card2icon.setScaledContents(True)
        self.card2icon.setObjectName("card2icon")
        self.label_43 = QtWidgets.QLabel(self.card2)
        self.label_43.setGeometry(QtCore.QRect(66, 130, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.totalPositivesLbl = QtWidgets.QLabel(self.card2)
        self.totalPositivesLbl.setGeometry(QtCore.QRect(30, 210, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalPositivesLbl.setFont(font)
        self.totalPositivesLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.totalPositivesLbl.setObjectName("totalPositivesLbl")
        self.card2btn = QtWidgets.QPushButton(self.card2)
        self.card2btn.setGeometry(QtCore.QRect(40, 26, 171, 111))
        self.card2btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/iconCovid/icons/covid/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card2btn.setIcon(icon10)
        self.card2btn.setIconSize(QtCore.QSize(100, 100))
        self.card2btn.setObjectName("card2btn")
        self.gridLayout_3.addWidget(self.card2, 0, 1, 1, 1)
        self.card5 = QtWidgets.QWidget(self.cardsFrame)
        self.card5.setMinimumSize(QtCore.QSize(250, 250))
        self.card5.setMaximumSize(QtCore.QSize(250, 250))
        self.card5.setObjectName("card5")
        self.card5icon = QtWidgets.QLabel(self.card5)
        self.card5icon.setGeometry(QtCore.QRect(40, 25, 170, 150))
        self.card5icon.setText("")
        self.card5icon.setScaledContents(True)
        self.card5icon.setObjectName("card5icon")
        self.label_46 = QtWidgets.QLabel(self.card5)
        self.label_46.setGeometry(QtCore.QRect(60, 130, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.totalRecoverecLbl = QtWidgets.QLabel(self.card5)
        self.totalRecoverecLbl.setGeometry(QtCore.QRect(30, 210, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalRecoverecLbl.setFont(font)
        self.totalRecoverecLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.totalRecoverecLbl.setObjectName("totalRecoverecLbl")
        self.card4btn = QtWidgets.QPushButton(self.card5)
        self.card4btn.setGeometry(QtCore.QRect(40, 26, 171, 111))
        self.card4btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/iconCovid/icons/covid/patient (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card4btn.setIcon(icon11)
        self.card4btn.setIconSize(QtCore.QSize(100, 100))
        self.card4btn.setObjectName("card4btn")
        self.gridLayout_3.addWidget(self.card5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.homePatientsTableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.homePatientsTableWidget.setGeometry(QtCore.QRect(20, 10, 1041, 461))
        self.homePatientsTableWidget.setObjectName("homePatientsTableWidget")
        self.homePatientsTableWidget.setColumnCount(7)
        self.homePatientsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.homePatientsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.homePatientsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.homePatientsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.homePatientsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.homePatientsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.homePatientsTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.homePatientsTableWidget.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.mainTabWidget.addTab(self.homeTab, "")
        self.patientsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patientsTab.sizePolicy().hasHeightForWidth())
        self.patientsTab.setSizePolicy(sizePolicy)
        self.patientsTab.setObjectName("patientsTab")
        self.patientsFrame = QtWidgets.QFrame(self.patientsTab)
        self.patientsFrame.setGeometry(QtCore.QRect(9, -1, 1061, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patientsFrame.sizePolicy().hasHeightForWidth())
        self.patientsFrame.setSizePolicy(sizePolicy)
        self.patientsFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.patientsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patientsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patientsFrame.setObjectName("patientsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.patientsFrame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.patientsListTab = QtWidgets.QTabWidget(self.patientsFrame)
        self.patientsListTab.setObjectName("patientsListTab")
        self.patientsListTab1 = QtWidgets.QWidget()
        self.patientsListTab1.setObjectName("patientsListTab1")
        self.widget = QtWidgets.QWidget(self.patientsListTab1)
        self.widget.setGeometry(QtCore.QRect(0, 10, 981, 61))
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.patientsTableWidget = QtWidgets.QTableWidget(self.patientsListTab1)
        self.patientsTableWidget.setGeometry(QtCore.QRect(0, 70, 1041, 471))
        self.patientsTableWidget.setObjectName("patientsTableWidget")
        self.patientsTableWidget.setColumnCount(7)
        self.patientsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.patientsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientsTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientsTableWidget.setHorizontalHeaderItem(6, item)
        self.patientsListTab.addTab(self.patientsListTab1, "")
        self.patientsListTab2 = QtWidgets.QWidget()
        self.patientsListTab2.setObjectName("patientsListTab2")
        self.patientsDettalLabel = QtWidgets.QWidget(self.patientsListTab2)
        self.patientsDettalLabel.setGeometry(QtCore.QRect(0, 10, 1011, 171))
        self.patientsDettalLabel.setObjectName("patientsDettalLabel")
        self.patientInfoLbl = QtWidgets.QLabel(self.patientsDettalLabel)
        self.patientInfoLbl.setGeometry(QtCore.QRect(20, 30, 700, 110))
        self.patientInfoLbl.setMinimumSize(QtCore.QSize(700, 110))
        self.patientInfoLbl.setMaximumSize(QtCore.QSize(700, 110))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.patientInfoLbl.setFont(font)
        self.patientInfoLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.patientInfoLbl.setObjectName("patientInfoLbl")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.patientsListTab2)
        self.scrollArea_3.setGeometry(QtCore.QRect(-1, 199, 1011, 391))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1003, 550))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(0, 550))
        self.scrollAreaWidgetContents_3.setMaximumSize(QtCore.QSize(16777215, 550))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.patientsDettalsTable = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.patientsDettalsTable.setGeometry(QtCore.QRect(10, 0, 981, 515))
        self.patientsDettalsTable.setMinimumSize(QtCore.QSize(0, 515))
        self.patientsDettalsTable.setMaximumSize(QtCore.QSize(16777215, 515))
        self.patientsDettalsTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patientsDettalsTable.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patientsDettalsTable.setObjectName("patientsDettalsTable")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.patientsDettalsTable)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_158 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_158.setFont(font)
        self.label_158.setObjectName("label_158")
        self.gridLayout_4.addWidget(self.label_158, 2, 0, 1, 1)
        self.label_188 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_188.setFont(font)
        self.label_188.setObjectName("label_188")
        self.gridLayout_4.addWidget(self.label_188, 3, 0, 1, 1)
        self.label_146 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.gridLayout_4.addWidget(self.label_146, 3, 1, 1, 2)
        self.label_186 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_186.setFont(font)
        self.label_186.setObjectName("label_186")
        self.gridLayout_4.addWidget(self.label_186, 1, 0, 1, 1)
        self.label_176 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_176.setFont(font)
        self.label_176.setObjectName("label_176")
        self.gridLayout_4.addWidget(self.label_176, 2, 1, 1, 2)
        self.label_177 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_177.setFont(font)
        self.label_177.setObjectName("label_177")
        self.gridLayout_4.addWidget(self.label_177, 1, 1, 1, 2)
        self.label_164 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_164.setFont(font)
        self.label_164.setObjectName("label_164")
        self.gridLayout_4.addWidget(self.label_164, 0, 0, 1, 1)
        self.label_152 = QtWidgets.QLabel(self.patientsDettalsTable)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_152.setFont(font)
        self.label_152.setObjectName("label_152")
        self.gridLayout_4.addWidget(self.label_152, 0, 1, 1, 2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.patientsListTab.addTab(self.patientsListTab2, "")
        self.verticalLayout_2.addWidget(self.patientsListTab)
        self.mainTabWidget.addTab(self.patientsTab, "")
        self.accountTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountTab.sizePolicy().hasHeightForWidth())
        self.accountTab.setSizePolicy(sizePolicy)
        self.accountTab.setMinimumSize(QtCore.QSize(1000, 0))
        self.accountTab.setObjectName("accountTab")
        self.frame_7 = QtWidgets.QFrame(self.accountTab)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1021, 4000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 4000))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 4000))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.accountHomeBtn = QtWidgets.QFrame(self.frame_7)
        self.accountHomeBtn.setGeometry(QtCore.QRect(0, 0, 1001, 171))
        self.accountHomeBtn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountHomeBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountHomeBtn.setObjectName("accountHomeBtn")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.accountHomeBtn)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_27 = QtWidgets.QWidget(self.accountHomeBtn)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.infoHomeBtn = QtWidgets.QPushButton(self.widget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoHomeBtn.sizePolicy().hasHeightForWidth())
        self.infoHomeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.infoHomeBtn.setFont(font)
        self.infoHomeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/others/user_information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoHomeBtn.setIcon(icon12)
        self.infoHomeBtn.setIconSize(QtCore.QSize(100, 100))
        self.infoHomeBtn.setObjectName("infoHomeBtn")
        self.horizontalLayout_9.addWidget(self.infoHomeBtn)
        self.horizontalLayout_14.addWidget(self.widget_27)
        self.accountFrame = QtWidgets.QFrame(self.frame_7)
        self.accountFrame.setGeometry(QtCore.QRect(0, 170, 1001, 411))
        self.accountFrame.setMinimumSize(QtCore.QSize(0, 400))
        self.accountFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountFrame.setObjectName("accountFrame")
        self.scrollArea = QtWidgets.QScrollArea(self.accountFrame)
        self.scrollArea.setGeometry(QtCore.QRect(-1, 0, 1001, 401))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 400))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 993, 4000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 4000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.accountInfoFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.accountInfoFrame.setGeometry(QtCore.QRect(1, 9, 990, 3991))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountInfoFrame.sizePolicy().hasHeightForWidth())
        self.accountInfoFrame.setSizePolicy(sizePolicy)
        self.accountInfoFrame.setMinimumSize(QtCore.QSize(990, 1000))
        self.accountInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountInfoFrame.setObjectName("accountInfoFrame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.accountInfoFrame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.infoFrame = QtWidgets.QFrame(self.accountInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoFrame.sizePolicy().hasHeightForWidth())
        self.infoFrame.setSizePolicy(sizePolicy)
        self.infoFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.infoFrame)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.infoContentFrame = QtWidgets.QFrame(self.infoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoContentFrame.sizePolicy().hasHeightForWidth())
        self.infoContentFrame.setSizePolicy(sizePolicy)
        self.infoContentFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.infoContentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoContentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoContentFrame.setObjectName("infoContentFrame")
        self.frame_11 = QtWidgets.QFrame(self.infoContentFrame)
        self.frame_11.setGeometry(QtCore.QRect(340, 20, 121, 171))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 67, 19))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setGeometry(QtCore.QRect(10, 90, 67, 19))
        self.label_16.setObjectName("label_16")
        self.label_26 = QtWidgets.QLabel(self.frame_11)
        self.label_26.setGeometry(QtCore.QRect(10, 140, 121, 31))
        self.label_26.setObjectName("label_26")
        self.frame_12 = QtWidgets.QFrame(self.infoContentFrame)
        self.frame_12.setGeometry(QtCore.QRect(460, 20, 271, 201))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.nom = QtWidgets.QLineEdit(self.frame_12)
        self.nom.setObjectName("nom")
        self.verticalLayout_29.addWidget(self.nom)
        self.prenom = QtWidgets.QLineEdit(self.frame_12)
        self.prenom.setObjectName("prenom")
        self.verticalLayout_29.addWidget(self.prenom)
        self.email = QtWidgets.QLineEdit(self.frame_12)
        self.email.setObjectName("email")
        self.verticalLayout_29.addWidget(self.email)
        self.infoContentSaveBtn = QtWidgets.QPushButton(self.infoContentFrame)
        self.infoContentSaveBtn.setGeometry(QtCore.QRect(500, 220, 181, 39))
        self.infoContentSaveBtn.setObjectName("infoContentSaveBtn")
        self.verticalLayout_26.addWidget(self.infoContentFrame)
        self.verticalLayout_21.addWidget(self.infoFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainTabWidget.addTab(self.accountTab, "")
        self.logoutTab = QtWidgets.QWidget()
        self.logoutTab.setObjectName("logoutTab")
        self.logoutTabFrame = QtWidgets.QFrame(self.logoutTab)
        self.logoutTabFrame.setGeometry(QtCore.QRect(10, 0, 1001, 641))
        self.logoutTabFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoutTabFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoutTabFrame.setObjectName("logoutTabFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.logoutTabFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_5 = QtWidgets.QFrame(self.logoutTabFrame)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 120))
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_17.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoutBtnNo = QtWidgets.QPushButton(self.frame_4)
        self.logoutBtnNo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutBtnNo.setObjectName("logoutBtnNo")
        self.horizontalLayout_2.addWidget(self.logoutBtnNo)
        self.logoutBtnYes = QtWidgets.QPushButton(self.frame_4)
        self.logoutBtnYes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutBtnYes.setObjectName("logoutBtnYes")
        self.horizontalLayout_2.addWidget(self.logoutBtnYes)
        self.verticalLayout_17.addWidget(self.frame_4)
        self.verticalLayout_12.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mainTabWidget.addTab(self.logoutTab, "")
        self.verticalLayout.addWidget(self.mainTabWidget, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.mainBody)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.mainTabWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        self.patientsListTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Espace médecin"))
        self.logoLbl.setText(_translate("mainWindow", "COVID 19"))
        self.homeBtn.setText(_translate("mainWindow", "  Accueil"))
        self.consultingBtn.setText(_translate("mainWindow", " Patients"))
        self.accountLeftBtn.setText(_translate("mainWindow", " Compte"))
        self.logoutBtn.setText(_translate("mainWindow", "Se déconnecter"))
        self.spaceLbl.setText(_translate("mainWindow", "Espace médecin"))
        self.welcomeLbl.setText(_translate("mainWindow", "Bienvenue medecin1!"))
        self.searchbar.setPlaceholderText(_translate("mainWindow", "Rechercher"))
        self.homePatientsLbl.setText(_translate("mainWindow", "Statistiques récentes"))
        self.label_24.setText(_translate("mainWindow", "TESTS"))
        self.totalTestsLbl.setText(_translate("mainWindow", "Total : 500"))
        self.label_34.setText(_translate("mainWindow", "CAS ACTIFS"))
        self.totalActivesLbl.setText(_translate("mainWindow", "Total : 500"))
        self.label_37.setText(_translate("mainWindow", "DÉCÈS"))
        self.totalDeathsLbl.setText(_translate("mainWindow", "Total : 500"))
        self.label_40.setText(_translate("mainWindow", "DOSES DE VACCIN"))
        self.totalDosesLbl.setText(_translate("mainWindow", "Total : 500"))
        self.label_43.setText(_translate("mainWindow", "CAS POSITIFS"))
        self.totalPositivesLbl.setText(_translate("mainWindow", "Total : 500"))
        self.label_46.setText(_translate("mainWindow", "CAS RÉTABLIES"))
        self.totalRecoverecLbl.setText(_translate("mainWindow", "Total : 500"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Tab 1"))
        item = self.homePatientsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "ID"))
        item = self.homePatientsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Nom"))
        item = self.homePatientsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Prénom"))
        item = self.homePatientsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Statut COVID19"))
        item = self.homePatientsTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Vaccination COVID19"))
        item = self.homePatientsTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Dernier test COVID19"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Tab 2"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.homeTab), _translate("mainWindow", "Acceuil"))
        self.label_3.setText(_translate("mainWindow", "Patients COVID19"))
        item = self.patientsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "ID"))
        item = self.patientsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Nom"))
        item = self.patientsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Prénom"))
        item = self.patientsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Statut COVID19"))
        item = self.patientsTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Vaccination COVID19"))
        item = self.patientsTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Dernier test COVID19"))
        self.patientsListTab.setTabText(self.patientsListTab.indexOf(self.patientsListTab1), _translate("mainWindow", "Liste patients"))
        self.patientInfoLbl.setText(_translate("mainWindow", "Karim Ben\n"
"45 ans\n"
"Sain\n"
"Vacciné (COVID19)"))
        self.label_158.setText(_translate("mainWindow", "Allergies"))
        self.label_188.setText(_translate("mainWindow", "Statut vaccinal"))
        self.label_146.setText(_translate("mainWindow", "- COVID 19 .\n"
"- BCG.\n"
"- Hépatite B.\n"
""))
        self.label_186.setText(_translate("mainWindow", "Antécédants chirurgiquaux"))
        self.label_176.setText(_translate("mainWindow", " OUI"))
        self.label_177.setText(_translate("mainWindow", "NON"))
        self.label_164.setText(_translate("mainWindow", "Antécédants médicaux"))
        self.label_152.setText(_translate("mainWindow", "- Antécédents cardiovasculaires.\n"
"- Asthmatique.\n"
"- Prise des anti-dépresseurs ou des neuroleptiques.\n"
"- Avoir un suivi dentaire régulier.\n"
""))
        self.patientsListTab.setTabText(self.patientsListTab.indexOf(self.patientsListTab2), _translate("mainWindow", "Détails patient"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.patientsTab), _translate("mainWindow", "Patients"))
        self.infoHomeBtn.setText(_translate("mainWindow", " Mes informations"))
        self.label_15.setText(_translate("mainWindow", "Nom :"))
        self.label_16.setText(_translate("mainWindow", "Prénom :"))
        self.label_26.setText(_translate("mainWindow", "Adresse e-mail :"))
        self.nom.setPlaceholderText(_translate("mainWindow", "Prénom"))
        self.prenom.setPlaceholderText(_translate("mainWindow", "Nom"))
        self.email.setPlaceholderText(_translate("mainWindow", "Téléphone"))
        self.infoContentSaveBtn.setText(_translate("mainWindow", "Sauvegarder"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.accountTab), _translate("mainWindow", "Compte"))
        self.label_5.setText(_translate("mainWindow", "Voulez-vous vraiment se déconnecter?"))
        self.logoutBtnNo.setText(_translate("mainWindow", "Non"))
        self.logoutBtnYes.setText(_translate("mainWindow", "Oui"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.logoutTab), _translate("mainWindow", "Se déconnecter"))
import resource_rc
