# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 630))
        MainWindow.setMaximumSize(QtCore.QSize(1054, 682))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1024, 630))
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 630))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("* {\n"
"    color: #000;\n"
"    border: none;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background-image: url(\":/images/images/login.png\");\n"
"    background-repeat: no repeat;\n"
"    color: #eff9fe;\n"
"}\n"
"\n"
"#formBg {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 15), stop:0.375 rgba(0, 0, 0, 55), stop:0.835227 rgba(0, 0, 0, 98));\n"
"}\n"
"\n"
"QLabel , #showPassword{\n"
"    color:#DED;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color:rgba(0, 0, 0, 80);\n"
"    border-radius: 6px;\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"    color:rgba(255, 255, 255, 230);\n"
"    padding:7px;\n"
"}\n"
"\n"
"QPushButton {    \n"
"    background-color: rgba(80, 80, 100, 150);\n"
"    color:rgba(155, 168, 182, 220);\n"
"    border-radius: 6px;\n"
"} \n"
"QPushButton:hover {    \n"
"    color:rgba(170, 192, 200, 250);\n"
"}\n"
"QPushButton:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115, 128, 142, 255);\n"
"}\n"
"\n"
"#errLbl {\n"
"    color: #F7BFB4;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.form = QtWidgets.QWidget(self.centralwidget)
        self.form.setMinimumSize(QtCore.QSize(400, 0))
        self.form.setObjectName("form")
        self.formBg = QtWidgets.QLabel(self.form)
        self.formBg.setGeometry(QtCore.QRect(1, 0, 400, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formBg.sizePolicy().hasHeightForWidth())
        self.formBg.setSizePolicy(sizePolicy)
        self.formBg.setMinimumSize(QtCore.QSize(400, 0))
        self.formBg.setText("")
        self.formBg.setObjectName("formBg")
        self.label = QtWidgets.QLabel(self.form)
        self.label.setGeometry(QtCore.QRect(140, 190, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(self.form)
        self.username.setGeometry(QtCore.QRect(100, 270, 211, 41))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.form)
        self.password.setGeometry(QtCore.QRect(100, 340, 211, 41))
        self.password.setObjectName("password")
        self.loginBtn = QtWidgets.QPushButton(self.form)
        self.loginBtn.setGeometry(QtCore.QRect(130, 420, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setObjectName("loginBtn")
        self.errLbl = QtWidgets.QLabel(self.form)
        self.errLbl.setGeometry(QtCore.QRect(10, 390, 381, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.errLbl.setFont(font)
        self.errLbl.setText("")
        self.errLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.errLbl.setObjectName("errLbl")
        self.password_eye = QtWidgets.QPushButton(self.form)
        self.password_eye.setGeometry(QtCore.QRect(280, 340, 31, 41))
        self.password_eye.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/others/hide_pw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_eye.setIcon(icon)
        self.password_eye.setIconSize(QtCore.QSize(30, 30))
        self.password_eye.setObjectName("password_eye")
        self.horizontalLayout.addWidget(self.form, 0, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Connexion"))
        self.label.setText(_translate("MainWindow", "Connexion"))
        self.username.setPlaceholderText(_translate("MainWindow", "Identifiant"))
        self.password.setPlaceholderText(_translate("MainWindow", "Mot de passe"))
        self.loginBtn.setText(_translate("MainWindow", "Se connecter"))
import resource_rc
